### ISSUE TITLE
docker镜像部署了跟最新版的不一致，是没更新还是我这边的问题呀

### ISSUE THREAD

**Issue by TWO-ICE** [doocs/docker-md#3]
如题
![2024-09-18_14-44-59](https://github.com/user-attachments/assets/7636ed50-57f5-4359-a083-1794e97b728a)

**Comment by yanglbme** [comment]
docker 镜像目前暂未更新，还是 md v1.6.0 的版本

**Comment by TWO-ICE** [comment]
感谢大佬回复，麻烦问下有更新计划吗？我等更新了再部署还是用着新版舒服一点

**Comment by yanglbme** [comment]
@TWO-ICE 我们镜像已更新，请重新拉取
